"""Frozen interfaces shared by every aivtube module (ARCHITECTURE.md §3, Appendix A).

Changing any contract needs an ADR in ``docs/adr`` and a ``CONTRACTS_VERSION`` bump.
Implementations import only ``contracts``, ``config`` and their own package.

The voice-worker names (``contracts.voice``: ``F32``, ``AudioOut``, ``TTSBackend``, …) are
re-exported lazily, so importing this package never imports numpy. IPC helpers
(``encode``/``decode``/``validate`` and the message-type constants) live in
``aivtube.contracts.ipc``.
"""

from typing import TYPE_CHECKING, Any

from aivtube.contracts.avatar import AvatarDriver, AvatarSink, AvatarState, LipTrack
from aivtube.contracts.chat import ChannelActions, ChatSelection, ChatSource, ChatWindow
from aivtube.contracts.control import ControlSurface, OpCommand, OpKind, OpResult
from aivtube.contracts.events import (
    EVENT_TYPES,
    Alert,
    BargeInCandidate,
    BargeInConfirmed,
    BargeInRejected,
    ChatDropped,
    ChatReceived,
    ComponentRestarted,
    DecisionAborted,
    DecisionStarted,
    EmotionChanged,
    Event,
    Filtered,
    GameActionResult,
    GameActionSent,
    GameConnected,
    GameContextReceived,
    GameDisconnected,
    GameForceReceived,
    HealthChanged,
    LatencyMark,
    LLMFirstToken,
    MemoryWritten,
    OperatorAction,
    ProviderSwitched,
    SegmentDone,
    SegmentQueued,
    SegmentStarted,
    StateChanged,
    StimulusExpired,
    StimulusQueued,
    SupportReceived,
    ToolExecuted,
    ToolRejected,
    ToolRequested,
    TurnTraceReady,
    UserSpeechEnded,
    UserSpeechStarted,
    UserTranscript,
    UtteranceDone,
    UtteranceStarted,
    event_from_json,
    event_to_json,
)
from aivtube.contracts.games import GameAction, GameBrain, GameForce, GameServer
from aivtube.contracts.infra import (
    Clock,
    Component,
    EventBus,
    Overflow,
    RestartPolicy,
    Subscription,
    TaskSupervisor,
)
from aivtube.contracts.ipc import IPC_VERSION, MESSAGE_SCHEMAS, Envelope, IpcError
from aivtube.contracts.llm import (
    ChatRequest,
    Done,
    LLMEvent,
    LLMProvider,
    LLMRouter,
    LocalServerManager,
    ProviderCaps,
    ProviderFailed,
    ProviderStatus,
    SlotRole,
    TextDelta,
    ToolCall,
    ToolSpec,
)
from aivtube.contracts.memory import (
    MemKind,
    MemoryItem,
    MemoryStore,
    MemSource,
    MemStatus,
    PrefixMemory,
    SlotsFull,
    Turn,
)
from aivtube.contracts.safety import (
    Classifier,
    Direction,
    FilterContext,
    FilterResult,
    SafetyGate,
    TextFilter,
    Verdict,
)
from aivtube.contracts.speech import (
    BargePolicy,
    EchoMode,
    MicMode,
    SpeechOutput,
    StopMode,
    TTSConstraints,
    VoicePolicy,
)
from aivtube.contracts.tools import (
    RateLimit,
    Risk,
    Tool,
    ToolContext,
    ToolPolicy,
    ToolRegistry,
    ToolResult,
)
from aivtube.contracts.types import (
    CONTRACTS_VERSION,
    ChatMessage,
    ChatUser,
    Health,
    HealthState,
    MsgKind,
    Platform,
    Priority,
    Rank,
    Segment,
    SegmentKind,
    Stimulus,
    StimulusKind,
    Transcript,
    VoiceSpec,
)

if TYPE_CHECKING:
    from aivtube.contracts.voice import (
        F32,
        I16,
        AudioBackend,
        AudioChunk,
        AudioIn,
        AudioOut,
        EchoCanceller,
        Endpointer,
        EndpointerConfig,
        MarkCallback,
        PhraseCache,
        QuotaSpec,
        SpeechRecognizer,
        TranscriptPostProcessor,
        TTSBackend,
        TTSUnavailable,
        VadEnd,
        VadEvent,
        VadPartial,
        VadStart,
        VoiceActivityDetector,
        WordMark,
    )

_LAZY_VOICE = frozenset(
    {
        "F32",
        "I16",
        "AudioBackend",
        "AudioChunk",
        "AudioIn",
        "AudioOut",
        "EchoCanceller",
        "Endpointer",
        "EndpointerConfig",
        "MarkCallback",
        "PhraseCache",
        "QuotaSpec",
        "SpeechRecognizer",
        "TTSBackend",
        "TTSUnavailable",
        "TranscriptPostProcessor",
        "VadEnd",
        "VadEvent",
        "VadPartial",
        "VadStart",
        "VoiceActivityDetector",
        "WordMark",
    }
)


def __getattr__(name: str) -> Any:
    if name in _LAZY_VOICE:
        from aivtube.contracts import voice

        value = getattr(voice, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | _LAZY_VOICE)


__all__ = [
    "CONTRACTS_VERSION",
    "EVENT_TYPES",
    "F32",
    "I16",
    "IPC_VERSION",
    "MESSAGE_SCHEMAS",
    "Alert",
    "AudioBackend",
    "AudioChunk",
    "AudioIn",
    "AudioOut",
    "AvatarDriver",
    "AvatarSink",
    "AvatarState",
    "BargeInCandidate",
    "BargeInConfirmed",
    "BargeInRejected",
    "BargePolicy",
    "ChannelActions",
    "ChatDropped",
    "ChatMessage",
    "ChatReceived",
    "ChatRequest",
    "ChatSelection",
    "ChatSource",
    "ChatUser",
    "ChatWindow",
    "Classifier",
    "Clock",
    "Component",
    "ComponentRestarted",
    "ControlSurface",
    "DecisionAborted",
    "DecisionStarted",
    "Direction",
    "Done",
    "EchoCanceller",
    "EchoMode",
    "EmotionChanged",
    "Endpointer",
    "EndpointerConfig",
    "Envelope",
    "Event",
    "EventBus",
    "FilterContext",
    "FilterResult",
    "Filtered",
    "GameAction",
    "GameActionResult",
    "GameActionSent",
    "GameBrain",
    "GameConnected",
    "GameContextReceived",
    "GameDisconnected",
    "GameForce",
    "GameForceReceived",
    "GameServer",
    "Health",
    "HealthChanged",
    "HealthState",
    "IpcError",
    "LLMEvent",
    "LLMFirstToken",
    "LLMProvider",
    "LLMRouter",
    "LatencyMark",
    "LipTrack",
    "LocalServerManager",
    "MarkCallback",
    "MemKind",
    "MemSource",
    "MemStatus",
    "MemoryItem",
    "MemoryStore",
    "MemoryWritten",
    "MicMode",
    "MsgKind",
    "OpCommand",
    "OpKind",
    "OpResult",
    "OperatorAction",
    "Overflow",
    "PhraseCache",
    "Platform",
    "PrefixMemory",
    "Priority",
    "ProviderCaps",
    "ProviderFailed",
    "ProviderStatus",
    "ProviderSwitched",
    "QuotaSpec",
    "Rank",
    "RateLimit",
    "RestartPolicy",
    "Risk",
    "SafetyGate",
    "Segment",
    "SegmentDone",
    "SegmentKind",
    "SegmentQueued",
    "SegmentStarted",
    "SlotRole",
    "SlotsFull",
    "SpeechOutput",
    "SpeechRecognizer",
    "StateChanged",
    "Stimulus",
    "StimulusExpired",
    "StimulusKind",
    "StimulusQueued",
    "StopMode",
    "Subscription",
    "SupportReceived",
    "TTSBackend",
    "TTSConstraints",
    "TTSUnavailable",
    "TaskSupervisor",
    "TextDelta",
    "TextFilter",
    "Tool",
    "ToolCall",
    "ToolContext",
    "ToolExecuted",
    "ToolPolicy",
    "ToolRegistry",
    "ToolRejected",
    "ToolRequested",
    "ToolResult",
    "ToolSpec",
    "Transcript",
    "TranscriptPostProcessor",
    "Turn",
    "TurnTraceReady",
    "UserSpeechEnded",
    "UserSpeechStarted",
    "UserTranscript",
    "UtteranceDone",
    "UtteranceStarted",
    "VadEnd",
    "VadEvent",
    "VadPartial",
    "VadStart",
    "Verdict",
    "VoiceActivityDetector",
    "VoicePolicy",
    "VoiceSpec",
    "WordMark",
    "event_from_json",
    "event_to_json",
]
